version: '3.9'

services:
  node-app:
    container_name: node-app
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    restart: always
    env_file: .env
    ports:
      - "${NODE_PORT}:3000"
    depends_on:
      - mysql
    networks:
      - app-network
    environment:
      - DB_HOST=mysql
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    env_file: .env
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
